about_us/urls.py
from django.urls import path
from . import views

app_name = 'about_us'
urlpatterns = [
    path('', views.about_us, name='about_us'),
    
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('mainpage.urls')),
    path('about_us/', include('about_us.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'
urlpatterns = [
    path('', views.mainpage, name='main'),
    
]

about_us/models.py
from django.db import models


class AboutImage(models.Model):
    name = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='about_us_img/',)
    
    def __str__(self) -> str:
        return self.name


class AboutText(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()

    def __str__(self) -> str:
        return self.title

mainpage/models.py
from django.db import models

# Create your models here.

about_us/views.py
from django.shortcuts import render
from . import models


def about_us(request):
    images = models.AboutImage.objects.all()
    text = models.AboutText.objects.all()
    context = {'images': images, 'text': text}
    return render(request, 'about_us/about_us.html', context=context)

mainpage/views.py
from django.shortcuts import render


def mainpage(request):
	return render(request, 'mainpage/main_page.html')

about_us/templates/about_us/about_us.html
{% extends 'mainpage/base.html' %}
{% load static %}
{% block title %}about us{%endblock%}

{% block content%}

этот файл расшыряет mainpage/base.html<br>
хедер и футер описывай там так как это будет повторятся на каждой страниц<br>
а в блоке контент - уникальный для каждой страницы контент

<p class="asd">images = {{ images }}</p>
<p>text = {{ text }}</p>

{% for image in images %}
    <p>image_name = {{ image.name }} </p>
    <img src="{{ image.picture.url }}">
{% endfor %}

{% for t in text %}
    <p> text_title = {{ t.title }} , full_text = {{ t.text }}</p>
{% endfor %}

{% endblock %}

mainpage/templates/mainpage/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <link rel="stylesheet" href="{% static 'about_us/css/about_us.css' %}">

    <link rel="stylesheet" href="{% static 'mainpage/css/main_page.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <title>{% block title %}Stone shop{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,700&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cuprum:ital@1&display=swap" rel="stylesheet">




    
    
</head>
<body>

        <header>
            <a href="{% url 'mainpage:main' %}">HOME</a><br>
            <a href="{% url 'about_us:about_us' %}">about us</a>
        </header>

        <main>

        {% block content %} {% endblock %}

        </main>



        <footer class="footer">
             <div class="footer_links">
                <a href="#" class="bottom_link">FAQ</a>
                <a href="#" class="bottom_link">RULES</a>
                <a href="#" class="bottom_link">OFFER</a>
                <a href="#" class="bottom_link">DELIVERY</a>
            </div>
                <div class="Asto">© Stone shop 2022</div>           
        </footer>
    </div>

    <script src="{% static 'about_us/js/about_us.js' %}"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

</body>
</html>

mainpage/templates/mainpage/main_page.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UK-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mainpage/css/main_page.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <title>{% block title %}Stone shop{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    

    <body>
        <h1 class="test">main page here</h1>
        
        <ul>
            <li><a href="{% url 'about_us:about_us' %}">about us</a></li>
            <li><a href="#">smth else</a></li>
        </ul>


    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="{% static 'mainpage/js/main_page.js' %}"></script>
    </body>
</html>